
lib: main.o mainMenu.o dispAll.o checkInBook.o constructor.o
	g++ -o lib main.o mainMenu.o dispAll.o checkInBook.o constructor.o

main.o: main.cpp class.cpp header.cpp declaration.cpp
	g++ -c main.cpp

mainMenu.o: mainMenu.cpp class.cpp header.cpp declaration.cpp
	g++ -c mainMenu.cpp

dispAll.o: dispAll.cpp class.cpp header.cpp declaration.cpp
	g++ -c dispAll.cpp

checkInBook.o: checkInBook.cpp class.cpp header.cpp declaration.cpp
	g++ -c checkInBook.cpp

constructor.o: constructor.cpp class.cpp header.cpp declaration.cpp
	g++ -c constructor.cpp






